%YAML:1.0

# image intput
Image.left.first   :  "../data/left01.png"
Image.left.second  :  "../data/left02.png"

Image.ORB_Features : 1
Image.SIFT_Features: 0
Image.SURF_Features: 0

Image.Resize: 0
Image.Stereo: 1

# ======================================================

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 707.0912
Camera.fy: 707.0912
Camera.cx: 601.8873
Camera.cy: 183.1104
# Camera.fx: 0.972222
# Camera.fy: 0.972222
# Camera.cx: 0.0
# Camera.cy: 0.0

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 1241
Camera.height: 376

# Camera frames per second
Camera.fps: 10.0

# Close/Far threshold. Baseline times.
ThDepth: 40

# ======================================================

# stereo baseline times fx
Stereo.bf: 379.8145
# the Th of depth is 30m
Stereo.th: 30000

# 0: SGBM
Stereo.MatchingMethod: 0

Stereo.right.first  :  "../data/right01.png"
Stereo.right.second :  "../data/right02.png"


